/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pxfg_gamingstore.newpackage.vista;

/**
 *
 * @author yisha
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitulo = new javax.swing.JLabel();
        ButtGClientes = new javax.swing.JButton();
        ButtGPersonal = new javax.swing.JButton();
        ButtonGProductos = new javax.swing.JButton();
        ButtSalir = new javax.swing.JButton();
        buttVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N

        labTitulo.setText("🕹️ PIXELFORGE - CONTROL DE INVENTARIO");
        labTitulo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 0)));

        ButtGClientes.setText("Gestion de Clientes");
        ButtGClientes.addActionListener(this::ButtGClientesActionPerformed);

        ButtGPersonal.setText("Gestion de Personal");
        ButtGPersonal.addActionListener(this::ButtGPersonalActionPerformed);

        ButtonGProductos.setText("Inventario de Productos");
        ButtonGProductos.addActionListener(this::ButtonGProductosActionPerformed);

        ButtSalir.setText("Salir del Sistema");
        ButtSalir.addActionListener(this::ButtSalirActionPerformed);

        buttVentas.setText("Caja Registradora");
        buttVentas.addActionListener(this::buttVentasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtGClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtGPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonGProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtGClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtGPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonGProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(ButtSalir)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtGPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtGPersonalActionPerformed
        // TODO add your handling code here:
        FormUsuarios ventanaUsuarios = new FormUsuarios();
ventanaUsuarios.setVisible(true);
    }//GEN-LAST:event_ButtGPersonalActionPerformed

    private void ButtGClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtGClientesActionPerformed
        // TODO add your handling code here:
        // Creamos la ventana de clientes
FormClientes ventanaClientes = new FormClientes();
// La hacemos visible
ventanaClientes.setVisible(true);
// (Opcional) Si quieres que el menú se oculte al abrir esta, descomenta la siguiente línea:
// this.setVisible(false);
    }//GEN-LAST:event_ButtGClientesActionPerformed

    private void ButtonGProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGProductosActionPerformed
        // TODO add your handling code here:
        FormProductos ventanaProductos = new FormProductos();
ventanaProductos.setVisible(true);
    }//GEN-LAST:event_ButtonGProductosActionPerformed

    private void buttVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttVentasActionPerformed
        // TODO add your handling code here:
        FormVentas ventanaVentas = new FormVentas();
ventanaVentas.setVisible(true);
    }//GEN-LAST:event_buttVentasActionPerformed

    private void ButtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtGClientes;
    private javax.swing.JButton ButtGPersonal;
    private javax.swing.JButton ButtSalir;
    private javax.swing.JButton ButtonGProductos;
    private javax.swing.JButton buttVentas;
    private javax.swing.JLabel labTitulo;
    // End of variables declaration//GEN-END:variables
}
